[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mtxc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
lexer = { path = "../lexer" }
anyhow.workspace = true
